[ycimpute](!https://github.com/OpenIDEA-YunanUniversity/ycimpute/blob/master/doc_eng.md)

In [9]:
import pandas as pd
import numpy as np
from ycimpute.imputer import iterforest

In [5]:
file = '../dataframes/tadolescente_enadis_2017_clean.csv'

In [6]:
df = pd.read_csv(filepath_or_buffer=file)

In [29]:
df.shape

(36192, 41)

In [7]:
df.head()

Unnamed: 0  pm6_1  pm6_2  pm6_3_1  pm6_3_2  pm6_3_3  pm6_3_4  pm6_3_5  \
0           0      1      1        1        1        2        1        1   
1           1      3      2        2        2        1        1        2   
2           2      2      7        1        1        2        1        1   
3           3      2      3        1        1        1        2        1   
4           4      1      3        2        1        1        2        1   

   pm8_1_1  pm8_1_2  ...   pm8_7_4  pm8_7_5  pm8_7_6  pm8_7_7  pm8_7_8  tloc  \
0        2        2  ...         2        2        2        2        2     1   
1        2        2  ...         2        2        2        2        2     1   
2        2        2  ...         2        2        2        2        2     1   
3        2        2  ...         2        2        2        2        2     1   
4        2        2  ...         2        2        2        2        2     1   

   estrato  ent  sexo  edad  
0        3    1     1    26  
1        3    1     1    26  
2        3    1     2    28  
3        3    1     2    29  
4        3    1     2    26  

[5 rows x 41 columns]

In [69]:
df_copy = df.copy()

In [70]:
df_copy.drop(labels=['Unnamed: 0'], axis=1, inplace=True)

In [71]:
df_copy.replace(to_replace=-1, value=np.nan, inplace=True)

In [72]:
no_missingdata = df_copy.columns[(df_copy.isnull().any() != True)].tolist()
no_missingdata

['tloc', 'estrato', 'ent', 'sexo', 'edad']

In [73]:
missingdata = df_copy.columns[df_copy.isnull().any()].tolist()
missingdata

['pm6_1',
 'pm6_2',
 'pm6_3_1',
 'pm6_3_2',
 'pm6_3_3',
 'pm6_3_4',
 'pm6_3_5',
 'pm8_1_1',
 'pm8_1_2',
 'pm8_1_3',
 'pm8_1_4',
 'pm8_1_5',
 'pm8_4_1',
 'pm8_4_2',
 'pm8_4_3',
 'pm8_4_4',
 'pm8_4_5',
 'pm8_6_01',
 'pm8_6_02',
 'pm8_6_03',
 'pm8_6_04',
 'pm8_6_05',
 'pm8_6_06',
 'pm8_6_07',
 'pm8_6_08',
 'pm8_6_09',
 'pm8_6_10',
 'pm8_7_1',
 'pm8_7_2',
 'pm8_7_3',
 'pm8_7_4',
 'pm8_7_5',
 'pm8_7_6',
 'pm8_7_7',
 'pm8_7_8']

## Impute `pm6_1`

In [16]:
column = 'pm6_1'

In [17]:
data_ = no_missingdata
data_

['tloc', 'estrato', 'ent', 'sexo', 'edad']

In [18]:
data_.append(column)

In [19]:
data_

['tloc', 'estrato', 'ent', 'sexo', 'edad', 'pm6_1']

In [21]:
index_na = pd.isnull(df_copy[data_]).any(1).nonzero()[0].tolist()
len(index_na)

358

In [22]:
(len(index_na)/df_copy.shape[0])*100

0.9891688770999116

In [23]:
df_data_ = df_copy[data_]
df_data_.head()

tloc  estrato  ent  sexo  edad  pm6_1
0     1        3    1     1    26    1.0
1     1        3    1     1    26    3.0
2     1        3    1     2    28    2.0
3     1        3    1     2    29    2.0
4     1        3    1     2    26    1.0

In [24]:
df_data_[column].unique()

array([ 1.,  3.,  2.,  4., nan,  9.])

In [25]:
impute_ = iterforest.IterImput().complete(df_data_.as_matrix())

C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [26]:
impute_

array([[ 1.,  3.,  1.,  1., 26.,  1.],
       [ 1.,  3.,  1.,  1., 26.,  3.],
       [ 1.,  3.,  1.,  2., 28.,  2.],
       ...,
       [ 4.,  2., 32.,  2., 16.,  1.],
       [ 4.,  2., 32.,  1., 16.,  4.],
       [ 4.,  2., 32.,  1., 12.,  2.]])

In [27]:
df_impute_ = pd.DataFrame(impute_)
df_impute_.head()

0    1    2    3     4    5
0  1.0  3.0  1.0  1.0  26.0  1.0
1  1.0  3.0  1.0  1.0  26.0  3.0
2  1.0  3.0  1.0  2.0  28.0  2.0
3  1.0  3.0  1.0  2.0  29.0  2.0
4  1.0  3.0  1.0  2.0  26.0  1.0

In [28]:
df_impute_.shape

(36192, 6)

In [30]:
df_impute_.isnull().any().any()

False

In [31]:
df_impute_ = df_impute_.astype('int64')

In [32]:
df_impute_.head()

0  1  2  3   4  5
0  1  3  1  1  26  1
1  1  3  1  1  26  3
2  1  3  1  2  28  2
3  1  3  1  2  29  2
4  1  3  1  2  26  1

In [33]:
df_copy[column] = df_impute_[5]

In [34]:
df_copy[column].unique()

array([1, 3, 2, 4, 9], dtype=int64)

## Impute `pm6_1`

In [76]:
len(no_missingdata)

6

In [77]:
i = 1
for column in df_copy[missingdata]:
    print(column)
    data_ = no_missingdata
    data_.append(column)
    index_na = pd.isnull(df_copy[data_]).any(1).nonzero()[0].tolist()
    df_data_ = df_copy[data_]
    impute_ = iterforest.IterImput().complete(df_data_.as_matrix())
    df_impute_ = pd.DataFrame(impute_)

    if (df_impute_.isnull().any().any() == False):
        df_impute_ = df_impute_.astype('int64')
        df_copy[column] = df_impute_[len(no_missingdata) - 1]
        

pm6_1


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm6_2


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm6_3_1


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm6_3_2


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm6_3_3


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm6_3_4


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm6_3_5


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_1_1


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_1_2


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_1_3


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_1_4


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_1_5


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_4_1


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_4_2


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_4_3


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_4_4


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_4_5


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_6_01


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_6_02


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_6_03


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_6_04


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_6_05


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_6_06


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_6_07


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_6_08


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_6_09


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_6_10


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_7_1


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_7_2


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_7_3


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_7_4


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_7_5


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_7_6


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_7_7


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


pm8_7_8


C:\Users\aniit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [78]:
df_copy.isnull().any().any()

False

In [79]:
df_copy.head()

pm6_1  pm6_2  pm6_3_1  pm6_3_2  pm6_3_3  pm6_3_4  pm6_3_5  pm8_1_1  \
0      1      1        1        1        2        1        1        2   
1      3      2        2        2        1        1        2        2   
2      2      7        1        1        2        1        1        2   
3      2      3        1        1        1        2        1        2   
4      1      3        2        1        1        2        1        2   

   pm8_1_2  pm8_1_3  ...   pm8_7_4  pm8_7_5  pm8_7_6  pm8_7_7  pm8_7_8  tloc  \
0        2        2  ...         2        2        2        2        2     1   
1        2        2  ...         2        2        2        2        2     1   
2        2        2  ...         2        2        2        2        2     1   
3        2        2  ...         2        2        2        2        2     1   
4        2        2  ...         2        2        2        2        2     1   

   estrato  ent  sexo  edad  
0        3    1     1    26  
1        3    1     1    26  
2        3    1     2    28  
3        3    1     2    29  
4        3    1     2    26  

[5 rows x 40 columns]

In [85]:
for column in df_copy:
    print(column, '\n', df_copy[column].value_counts())

pm6_1 
 2    16453
3    11141
1     6960
4     1539
9       99
Name: pm6_1, dtype: int64
pm6_2 
 3    12538
2     7512
1     4811
4     3368
5     3071
7     2699
6     2107
8       86
Name: pm6_2, dtype: int64
pm6_3_1 
 2    18310
1    17744
9      135
5        1
4        1
3        1
Name: pm6_3_1, dtype: int64
pm6_3_2 
 1    20956
2    14747
9      481
5        3
3        3
4        2
Name: pm6_3_2, dtype: int64
pm6_3_3 
 1    18224
2    17670
9      296
4        1
3        1
Name: pm6_3_3, dtype: int64
pm6_3_4 
 1    26346
2     9606
9      236
4        4
Name: pm6_3_4, dtype: int64
pm6_3_5 
 1    28492
2     7578
9      122
Name: pm6_3_5, dtype: int64
pm8_1_1 
 2    33249
1     2038
3      905
Name: pm8_1_1, dtype: int64
pm8_1_2 
 2    25711
3     9086
1     1395
Name: pm8_1_2, dtype: int64
pm8_1_3 
 2    34961
1      665
3      566
Name: pm8_1_3, dtype: int64
pm8_1_4 
 2    20569
3    12854
1     2769
Name: pm8_1_4, dtype: int64
pm8_1_5 
 2    32811
3     2392
1      989
Name: pm

In [86]:
df_copy.to_csv('../dataframes/tadolescente_enadis_2017_impute.csv')